# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f32c150638a0517e26eacff8738695ef511652938355fd0040bac64d907450a70cd2c84a4471b23ccccce095ff3dd3e5e9c94e6dc98c691bde01a3413b008cda

test:
  secret_key_base: a1bf3a77567985221ca85b8a73c5eeab82c21404059ad1f955b5293b6bd793fdd9cb70703e30a00045e731fad5e9094773bba2f9cc5e30eadd03ea0b4e13d8de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
